const c=document.getElementById("game"),x=c.getContext("2d");let d=1,W=2400,H=2400,mode="royale",running=false,selectedSkin="default",coins=500,level=1,inventory={skins:["default"],picks:["pixel"],owned:["default","pixel"]},p={x:1200,y:1200,r:16,s:3.4,health:100,shield:100,angle:0,weapon:0},cam={x:0,y:0},moveJoy={x:0,y:0},aimJoy={x:0,y:0},keys={},objs=[],enemies=[],bullets=[],wood=0,stone=0,metal=0,lastHit=0,score=0,alive=12,toastTimer=0;
const skins=[{id:"default",name:"RIFT DEFAULT",price:0,cls:"",icon:"🧑"},{id:"neon",name:"NEON RUNNER",price:250,cls:"skin-neon",icon:"🟣"},{id:"shadow",name:"SHADOWBYTE",price:350,cls:"skin-shadow",icon:"🌑"},{id:"sunset",name:"SUNSET PIXEL",price:450,cls:"skin-sunset",icon:"🌅"}];
const picks=[{id:"pixel",name:"PIXEL PICKAXE",icon:"⛏️"},{id:"star",name:"STAR BREAKER",icon:"⭐"}];
const items=[{id:"blaster",name:"PIXEL BLASTER",icon:"🔫",rarity:"Rare",price:0},{id:"medkit",name:"MINI MED",icon:"🩹",rarity:"Common",price:75},{id:"shield",name:"SHIELD CELL",icon:"🛡️",rarity:"Rare",price:100},{id:"slurp",name:"SLURP JUICE",icon:"🧪",rarity:"Epic",price:150}];
function save(){localStorage.riftSave=JSON.stringify({coins,level,inventory,selectedSkin})}function load(){try{let z=JSON.parse(localStorage.riftSave);if(z){coins=z.coins??500;level=z.level??1;inventory=z.inventory??inventory;selectedSkin=z.selectedSkin??"default"}}catch{}}
function resize(){d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();load();coins=Number(coins);
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),1400)}
function avatar(id,el){el.className="pixel-avatar "+(skins.find(s=>s.id===id)?.cls||"")}
function renderLobby(){document.getElementById("coins").textContent="🪙 "+coins;document.getElementById("level").textContent="LVL "+level;avatar(selectedSkin,document.getElementById("lobbyAvatar"))}
function renderLocker(){avatar(selectedSkin,document.getElementById("lockerAvatar"));document.getElementById("skinName").textContent=skins.find(s=>s.id===selectedSkin).name;document.getElementById("equipBtn").textContent="EQUIPPED";document.getElementById("skinGrid").innerHTML=skins.map(s=>`<button class="item ${selectedSkin===s.id?"selected":""}" data-skin="${s.id}"><div class="icon">${s.icon}</div><b>${s.name}</b><small>${inventory.skins.includes(s.id)?"OWNED":s.price+" coins"}</small></button>`).join("");document.getElementById("pickGrid").innerHTML=picks.map(s=>`<button class="item"><div class="icon">${s.icon}</div><b>${s.name}</b><small>OWNED</small></button>`).join("");document.querySelectorAll("[data-skin]").forEach(b=>b.onclick=()=>{let id=b.dataset.skin;if(!inventory.skins.includes(id)){let s=skins.find(q=>q.id===id);if(coins<s.price)return toast("Not enough coins");coins-=s.price;inventory.skins.push(id)}selectedSkin=id;save();renderLocker();renderLobby()})}
function renderShop(){document.getElementById("shopCoins").textContent=coins;document.getElementById("shopGrid").innerHTML=items.map(i=>`<button class="item" data-item="${i.id}"><div class="icon">${i.icon}</div><b>${i.name}</b><small>${i.rarity} • ${i.price?i.price+" coins":"FREE"}</small></button>`).join("");document.querySelectorAll("[data-item]").forEach(b=>b.onclick=()=>{let i=items.find(q=>q.id===b.dataset.item);if(i.price&&coins<i.price)return toast("Not enough coins");if(i.price)coins-=i.price;save();renderShop();toast(i.name+" added to inventory")})}
function openScreen(id){document.querySelectorAll(".screen").forEach(e=>e.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");if(id==="locker")renderLocker();if(id==="shop")renderShop()}
document.querySelectorAll(".mode-card").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mode-card").forEach(q=>q.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode});
document.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>openScreen(b.dataset.screen));document.querySelectorAll(".back").forEach(b=>b.onclick=()=>{openScreen("lobby");renderLobby()});
document.getElementById("playBtn").onclick=()=>startGame();document.getElementById("leave").onclick=()=>{running=false;document.getElementById("gameScreen").classList.add("hidden");openScreen("lobby");renderLobby()};
document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{b.classList.toggle("on");b.querySelector("b").textContent=b.classList.contains("on")?"ON":"OFF"});
document.getElementById("resetData").onclick=()=>{localStorage.removeItem("riftSave");coins=500;level=1;inventory={skins:["default"],picks:["pixel"],owned:["default","pixel"]};selectedSkin="default";renderLobby();toast("Progress reset")};
function setupWorld(){objs=[];enemies=[];bullets=[];wood=stone=metal=0;score=0;alive=mode==="royale"?12:mode==="duel"?2:mode==="rumble"?8:2;p={x:1200,y:1200,r:16,s:3.4,health:100,shield:100,angle:0,weapon:0};let count=mode==="duel"?45:110;for(let i=0;i<count;i++)objs.push({x:50+Math.random()*2300,y:50+Math.random()*2300,t:Math.random()<.7?"tree":"rock",hp:3});let ec=mode==="duel"?1:mode==="rumble"?7:mode==="royale"?11:1;for(let i=0;i<ec;i++)enemies.push({x:300+Math.random()*1800,y:300+Math.random()*1800,hp:100,cd:0,angle:0})}
function startGame(){document.querySelectorAll(".screen").forEach(e=>e.classList.add("hidden"));document.getElementById("gameScreen").classList.remove("hidden");running=true;setupWorld();document.getElementById("modeLabel").textContent={royale:"BATTLE ROYALE",duel:"1V1 DUEL",build:"BUILD FIGHT",rumble:"TEAM RUMBLE"}[mode];document.getElementById("objective").textContent=mode==="royale"?"LOOT UP":mode==="duel"?"ELIMINATE ENEMY":mode==="build"?"BUILD & EDIT":"GET 10 KOs";renderHotbar();toast("DROP IN!");}
function renderHotbar(){document.getElementById("hotbar").innerHTML=["🔫","🩹","🛡️","⛏️","🧱"].map((v,i)=>`<button class="slot ${i===0?"active":""}" data-slot="${i}">${v}</button>`).join("");document.querySelectorAll("[data-slot]").forEach(b=>b.onclick=()=>{p.weapon=+b.dataset.slot;document.querySelectorAll(".slot").forEach(q=>q.classList.remove("active"));b.classList.add("active")})}
function loop(){if(!running)return;let w=innerWidth,h=innerHeight;cam.x=Math.max(0,Math.min(W-w,p.x-w/2));cam.y=Math.max(0,Math.min(H-h,p.y-h/2));x.clearRect(0,0,w,h);x.fillStyle="#62bd5d";x.fillRect(0,0,w,h);for(let yy=Math.floor(cam.y/32)*32;yy<cam.y+h+32;yy+=32)for(let xx=Math.floor(cam.x/32)*32;xx<cam.x+w+32;xx+=32){x.fillStyle=((xx/32+yy/32)%2?"#60b85a":"#66c45f");x.fillRect(xx-cam.x,yy-cam.y,32,32)}if(mode==="royale"){x.fillStyle="#329bd6";x.beginPath();x.ellipse(1250-cam.x,1200-cam.y,420,230,0,0,7);x.fill()}objs.forEach(o=>{let a=o.x-cam.x,b=o.y-cam.y;if(o.t==="tree"){x.fillStyle="#6f492f";x.fillRect(a-5,b+5,10,25);x.fillStyle="#27783d";x.fillRect(a-20,b-20,40,34);x.fillStyle="#3e9b4d";x.fillRect(a-13,b-28,26,15)}else{x.fillStyle="#70777c";x.fillRect(a-17,b-11,34,22);x.fillStyle="#9aa1a4";x.fillRect(a-9,b-16,18,9)}});enemies.forEach(e=>{let a=e.x-cam.x,b=e.y-cam.y;x.fillStyle="#e35b67";x.fillRect(a-13,b-15,26,30);x.fillStyle="#fff";x.fillRect(a+6,b-4,5,5);if(e.hp<100){x.fillStyle="#161820";x.fillRect(a-15,b-25,30,4);x.fillStyle="#58d45b";x.fillRect(a-15,b-25,30*(e.hp/100),4)}});bullets.forEach(b=>{x.fillStyle="#ffe36e";x.fillRect(b.x-cam.x-3,b.y-cam.y-3,6,6)});let px=p.x-cam.x,py=p.y-cam.y;x.save();x.translate(px,py);x.rotate(p.angle);x.fillStyle=skins.find(s=>s.id===selectedSkin).id==="shadow"?"#8d96a8":skins.find(s=>s.id===selectedSkin).id==="neon"?"#b8f7ff":"#f1c6a5";x.fillRect(-12,-15,24,30);x.fillStyle="#5b3a29";x.fillRect(-13,-19,26,9);x.fillStyle="#fff";x.fillRect(9,-3,24,6);x.restore();if(Date.now()-lastHit<120){x.strokeStyle="#fff";x.lineWidth=4;x.beginPath();x.arc(px+Math.cos(p.angle)*42,py+Math.sin(p.angle)*42,12,0,7);x.stroke()}requestAnimationFrame(loop)}
function update(){if(!running)return;let a=(keys.d?1:0)-(keys.a?1:0)+moveJoy.x,b=(keys.s?1:0)-(keys.w?1:0)+moveJoy.y,m=Math.hypot(a,b);if(m){a/=m;b/=m;p.x=Math.max(20,Math.min(W-20,p.x+a*p.s));p.y=Math.max(20,Math.min(H-20,p.y+b*p.s))}enemies.forEach(e=>{let dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy);if(dist>130){e.x+=dx/dist*1.1;e.y+=dy/dist*1.1}e.angle=Math.atan2(dy,dx);if(dist<300&&Date.now()>e.cd){e.cd=Date.now()+900;bullets.push({x:e.x,y:e.y,dx:dx/dist*4,dy:dy/dist*4,enemy:true})}});bullets.forEach((b,i)=>{b.x+=b.dx;b.y+=b.dy;if(Math.hypot(b.x-p.x,b.y-p.y)<18&&b.enemy){p.shield>0?p.shield-=8:p.health-=8;bullets.splice(i,1)}});bullets.forEach((b,i)=>{for(const e of enemies)if(!b.enemy&&Math.hypot(b.x-e.x,b.y-e.y)<20){e.hp-=35;bullets.splice(i,1);if(e.hp<=0){enemies.splice(enemies.indexOf(e),1);score++;alive=Math.max(1,alive-1);coins+=10;toast("+10 coins • ELIMINATION")}}});if(mode==="rumble"&&score>=10){endMatch(true)}if(mode==="duel"&&enemies.length===0){endMatch(true)}if(mode==="royale"&&enemies.length===0){endMatch(true)}if(p.health<=0)endMatch(false);document.getElementById("health").style.width=Math.max(0,p.health)+"%";document.getElementById("shield").style.width=Math.max(0,p.shield)+"%";document.getElementById("wood").textContent=wood;document.getElementById("stone").textContent=stone;document.getElementById("metal").textContent=metal;document.getElementById("alive").textContent="ALIVE "+Math.max(1,alive);requestAnimationFrame(update)}
function shoot(){if(!running)return;let a=p.angle;bullets.push({x:p.x+Math.cos(a)*25,y:p.y+Math.sin(a)*25,dx:Math.cos(a)*8,dy:Math.sin(a)*8,enemy:false});}
function action(){if(!running)return;let best=null,bestDist=85;for(const o of objs){let dist=Math.hypot(o.x-p.x,o.y-p.y),ang=Math.atan2(o.y-p.y,o.x-p.x),diff=Math.atan2(Math.sin(ang-p.angle),Math.cos(ang-p.angle));if(dist<bestDist&&Math.abs(diff)<.9){best=o;bestDist=dist}}if(best){best.hp--;lastHit=Date.now();if(best.hp<=0){if(best.t==="tree")wood+=10;else stone+=8;objs.splice(objs.indexOf(best),1);toast(best.t==="tree"?"+10 WOOD":"+8 STONE")}}}
function endMatch(win){running=false;coins+=win?50:10;level+=win?1:0;save();toast(win?"VICTORY! +50 COINS":"ELIMINATED");setTimeout(()=>{document.getElementById("gameScreen").classList.add("hidden");openScreen("lobby");renderLobby()},900)}
function bindStick(id,knobId,type){const stick=document.getElementById(id),knob=document.getElementById(knobId);let active=false;function setJoy(e){const t=e.touches[0],r=stick.getBoundingClientRect();let a=t.clientX-(r.left+r.width/2),b=t.clientY-(r.top+r.height/2),m=Math.hypot(a,b),z=48;if(m>z){a=a/m*z;b=b/m*z}if(type==="move"){moveJoy.x=a/z;moveJoy.y=b/z}else{aimJoy.x=a/z;aimJoy.y=b/z;if(m>5)p.angle=Math.atan2(b,a)}knob.style.transform="translate("+a+"px,"+b+"px)"}stick.addEventListener("touchstart",e=>{active=true;setJoy(e);e.preventDefault()},{passive:false});stick.addEventListener("touchmove",e=>{if(active){setJoy(e);e.preventDefault()}},{passive:false});stick.addEventListener("touchend",()=>{active=false;if(type==="move"){moveJoy.x=moveJoy.y=0}else aimJoy.x=aimJoy.y=0;knob.style.transform="translate(0,0)"})}bindStick("moveStick","moveKnob","move");bindStick("aimStick","aimKnob","aim");document.getElementById("action").addEventListener("touchstart",e=>{e.preventDefault();action()},{passive:false});document.getElementById("shoot").addEventListener("touchstart",e=>{e.preventDefault();shoot()},{passive:false});document.getElementById("build").addEventListener("touchstart",e=>{e.preventDefault();toast(mode==="build"?"BUILD PIECE SELECTED":"Build mode coming next")},{passive:false});addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=1;if(e.key===" "||e.key.toLowerCase()==="k")shoot();if(e.key.toLowerCase()==="e")action()});addEventListener("keyup",e=>keys[e.key.toLowerCase()]=0);renderLobby();