const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
const SAVE_KEY="riftSave"; const WORLD=2400; const TILE=32;
let DPR=1,modeName=new URLSearchParams(location.search).get("mode")||"royale";
let mode={}; let running=true,last=performance.now(),toastTimer=0;
const s={player:{x:1200,y:1200,r:14,speed:210,health:100,shield:100,angle:0},enemies:[],objects:[],bullets:[],loot:[],structures:[],keys:{},move:{x:0,y:0},aim:{x:0,y:0},wood:100,stone:50,metal:0,kills:0,score:0,alive:1,buildMode:false,storm:{x:1200,y:1200,r:1100},selectedSkin:"default"};
function resize(){DPR=devicePixelRatio||1;canvas.width=innerWidth*DPR;canvas.height=innerHeight*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener("resize",resize);resize();
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");s.selectedSkin=d.selectedSkin||"default"}catch{}}
function saveReward(win){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");d.coins=Number(d.coins||500)+(win?50:10);d.level=Number(d.level||1)+(win?1:0);localStorage.setItem(SAVE_KEY,JSON.stringify(d))}catch{}}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),1300)}
function spawnEnemy(team="enemy"){let a=Math.random()*Math.PI*2,r=450+Math.random()*650; s.enemies.push({x:1200+Math.cos(a)*r,y:1200+Math.sin(a)*r,r:14,hp:100,maxHp:100,team,cd:0,angle:0,dead:false})}
function spawnWorld(){s.objects=[];for(let i=0;i<105;i++)s.objects.push({x:40+Math.random()*2320,y:40+Math.random()*2320,type:Math.random()<.7?"tree":"rock",hp:3});for(let i=0;i<20;i++)s.loot.push({x:100+Math.random()*2200,y:100+Math.random()*2200,type:Math.random()<.5?"shield":"med"})}
function fire(owner,enemy=false){const a=owner.angle;s.bullets.push({x:owner.x+Math.cos(a)*22,y:owner.y+Math.sin(a)*22,dx:Math.cos(a)*620,dy:Math.sin(a)*620,enemy})}
function damagePlayer(n){if(s.player.shield>0){const q=Math.min(s.player.shield,n);s.player.shield-=q;n-=q}s.player.health-=n}
function shoot(){if(!running)return;fire(s.player,false)}
function placeBuild(){if(!running)return;if(modeName!=="build")return toast("Build Fight only");if(s.wood<10)return toast("Need 10 wood");let gx=Math.round((s.player.x+Math.cos(s.player.angle)*64)/TILE)*TILE,gy=Math.round((s.player.y+Math.sin(s.player.angle)*64)/TILE)*TILE;s.structures.push({x:gx,y:gy,w:64,h:16,hp:200});s.wood-=10;toast("WALL BUILT")}
function mine(){if(!running)return;if(modeName==="build"&&s.buildMode)return placeBuild();let best=null,bd=78;for(const o of s.objects){const d=Math.hypot(o.x-s.player.x,o.y-s.player.y);if(d<bd){const a=Math.atan2(o.y-s.player.y,o.x-s.player.x),diff=Math.abs(Math.atan2(Math.sin(a-s.player.angle),Math.cos(a-s.player.angle)));if(diff<1){best=o;bd=d}}}if(!best)return;best.hp--;if(best.hp<=0){if(best.type==="tree")s.wood+=10;else s.stone+=8;s.objects.splice(s.objects.indexOf(best),1);toast(best.type==="tree"?"+10 WOOD":"+8 STONE")}}
function pickLoot(){for(const l of [...s.loot])if(Math.hypot(l.x-s.player.x,l.y-s.player.y)<28){if(l.type==="med")s.player.health=Math.min(100,s.player.health+35);else s.player.shield=Math.min(100,s.player.shield+35);s.loot.splice(s.loot.indexOf(l),1)}}
function playerHitEnemy(b){for(const e of s.enemies){if(e.dead||e.team==="ally")continue;if(Math.hypot(b.x-e.x,b.y-e.y)<20){e.hp-=35;return e}}return null}
function end(win){if(!running)return;running=false;saveReward(win);toast(win?"VICTORY! +50 COINS":"ELIMINATED");setTimeout(()=>location.href="index.html",800)}
function tick(dt){const p=s.player;let mx=(s.keys.d?1:0)-(s.keys.a?1:0)+s.move.x,my=(s.keys.s?1:0)-(s.keys.w?1:0)+s.move.y,m=Math.hypot(mx,my);if(m){mx/=m;my/=m;p.x=Math.max(20,Math.min(WORLD-20,p.x+mx*p.speed*dt));p.y=Math.max(20,Math.min(WORLD-20,p.y+my*p.speed*dt))}
if(Math.hypot(s.aim.x,s.aim.y)>.15)p.angle=Math.atan2(s.aim.y,s.aim.x);
for(const e of s.enemies){if(e.dead)continue;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);if(e.team!=="ally"){if(d>125){e.x+=dx/d*72*dt;e.y+=dy/d*72*dt}e.angle=Math.atan2(dy,dx);if(d<520&&performance.now()>e.cd){e.cd=performance.now()+850+Math.random()*400;fire(e,true)}}else if(d>120){e.x+=(p.x-e.x)/d*45*dt;e.y+=(p.y-e.y)/d*45*dt}}
for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.x+=b.dx*dt;b.y+=b.dy*dt;let remove=b.x<0||b.y<0||b.x>WORLD||b.y>WORLD;if(b.enemy&&Math.hypot(b.x-p.x,b.y-p.y)<18){damagePlayer(8);remove=true}else if(!b.enemy){const hit=playerHitEnemy(b);if(hit){hit.hp-=0;remove=true;if(hit.hp<=0){hit.dead=true;s.kills++;s.score++;s.loot.push({x:hit.x,y:hit.y,type:Math.random()<.5?"shield":"med"});toast("+1 ELIMINATION")}}}if(remove)s.bullets.splice(i,1)}
for(const e of s.enemies)if(e.dead&&modeName==="rumble"){setTimeout(()=>{if(running){e.dead=false;e.hp=100;e.x=200+Math.random()*2000;e.y=200+Math.random()*2000}},700)}
pickLoot();mode.tick?.(dt);
if(p.health<=0)end(false);
document.getElementById("health").style.width=Math.max(0,p.health)+"%";document.getElementById("shield").style.width=Math.max(0,p.shield)+"%";document.getElementById("wood").textContent=s.wood;document.getElementById("stone").textContent=s.stone;document.getElementById("metal").textContent=s.metal;document.getElementById("alive").textContent=modeName==="rumble"?"KOs "+s.score:"ALIVE "+Math.max(1,s.enemies.filter(e=>!e.dead).length+1)}
function draw(){const w=innerWidth,h=innerHeight,p=s.player,camX=Math.max(0,Math.min(WORLD-w,p.x-w/2)),camY=Math.max(0,Math.min(WORLD-h,p.y-h/2));ctx.clearRect(0,0,w,h);ctx.fillStyle="#62bd5d";ctx.fillRect(0,0,w,h);
for(let y=Math.floor(camY/TILE)*TILE;y<camY+h+TILE;y+=TILE)for(let x=Math.floor(camX/TILE)*TILE;x<camX+w+TILE;x+=TILE){ctx.fillStyle=((x/TILE+y/TILE)%2?"#60b85a":"#66c45f");ctx.fillRect(x-camX,y-camY,TILE,TILE)}
mode.draw?.(ctx,camX,camY);
for(const o of s.objects){const a=o.x-camX,b=o.y-camY;if(o.type==="tree"){ctx.fillStyle="#6f492f";ctx.fillRect(a-5,b+5,10,25);ctx.fillStyle="#27783d";ctx.fillRect(a-20,b-20,40,34)}else{ctx.fillStyle="#70777c";ctx.fillRect(a-17,b-11,34,22);ctx.fillStyle="#9aa1a4";ctx.fillRect(a-9,b-16,18,9)}}
for(const l of s.loot){ctx.fillStyle=l.type==="med"?"#ff7777":"#48b8ff";ctx.fillRect(l.x-camX-8,l.y-camY-8,16,16)}
for(const b of s.bullets){ctx.fillStyle=b.enemy?"#ff7676":"#ffe36e";ctx.fillRect(b.x-camX-3,b.y-camY-3,6,6)}
for(const e of s.enemies)if(!e.dead){ctx.fillStyle=e.team==="ally"?"#4e9dff":"#e35b67";ctx.fillRect(e.x-camX-13,e.y-camY-15,26,30);ctx.fillStyle="#18202a";ctx.fillRect(e.x-camX-15,e.y-camY-25,30,4);ctx.fillStyle="#58d45b";ctx.fillRect(e.x-camX-15,e.y-camY-25,30*Math.max(0,e.hp/100),4)}
for(const q of s.structures){ctx.fillStyle="#b77842";ctx.fillRect(q.x-camX-q.w/2,q.y-camY-q.h/2,q.w,q.h);ctx.strokeStyle="#704321";ctx.strokeRect(q.x-camX-q.w/2,q.y-camY-q.h/2,q.w,q.h)}
ctx.save();ctx.translate(p.x-camX,p.y-camY);ctx.rotate(p.angle);let body=s.selectedSkin==="neon"?"#b8f7ff":s.selectedSkin==="shadow"?"#8d96a8":s.selectedSkin==="sunset"?"#f3b08d":"#f1c6a5";ctx.fillStyle=body;ctx.fillRect(-12,-15,24,30);ctx.fillStyle=s.selectedSkin==="shadow"?"#161a25":"#5b3a29";ctx.fillRect(-13,-19,26,9);ctx.fillStyle="#fff";ctx.fillRect(9,-3,24,6);ctx.restore();
requestAnimationFrame(frame)}
function frame(now){if(!running)return;const dt=Math.min(.033,(now-last)/1000);last=now;tick(dt);draw()}
function bindStick(id,knobId,type){const stick=document.getElementById(id),knob=document.getElementById(knobId);let active=false;const set=e=>{const t=e.touches[0],r=stick.getBoundingClientRect();let a=t.clientX-r.left-r.width/2,b=t.clientY-r.top-r.height/2,m=Math.hypot(a,b),z=48;if(m>z){a=a/m*z;b=b/m*z}if(type==="move"){s.move.x=a/z;s.move.y=b/z}else{s.aim.x=a/z;s.aim.y=b/z}knob.style.transform=`translate(${a}px,${b}px)`};stick.addEventListener("touchstart",e=>{active=true;set(e);e.preventDefault()},{passive:false});stick.addEventListener("touchmove",e=>{if(active){set(e);e.preventDefault()}},{passive:false});stick.addEventListener("touchend",()=>{active=false;if(type==="move")s.move.x=s.move.y=0;else s.aim.x=s.aim.y=0;knob.style.transform="translate(0,0)"})}
document.getElementById("shoot").addEventListener("touchstart",e=>{e.preventDefault();shoot()},{passive:false});document.getElementById("action").addEventListener("touchstart",e=>{e.preventDefault();mine()},{passive:false});document.getElementById("build").addEventListener("touchstart",e=>{e.preventDefault();s.buildMode=!s.buildMode;toast(s.buildMode?"BUILD MODE":"COMBAT MODE")},{passive:false});
document.getElementById("leave").onclick=()=>location.href="index.html";
addEventListener("keydown",e=>{s.keys[e.key.toLowerCase()]=true;if(e.key===" ")shoot();if(e.key.toLowerCase()==="e")mine();if(e.key.toLowerCase()==="q")placeBuild()});addEventListener("keyup",e=>s.keys[e.key.toLowerCase()]=false);
bindStick("moveStick","moveKnob","move");bindStick("aimStick","aimKnob","aim");load();spawnWorld();
const moduleUrl="./modes/"+modeName+".js";
try{mode=await import(moduleUrl);mode.init?.(s,{spawnEnemy,toast,end});document.getElementById("modeLabel").textContent=mode.label;document.getElementById("objective").textContent=mode.objective;document.getElementById("hotbar").innerHTML=["🔫","🩹","🛡️","⛏️","🧱"].map((v,i)=>`<button class="slot ${i===0?"active":""}">${v}</button>`).join("");toast("DROP IN!");frame(performance.now())}catch(err){console.error(err);toast("MODE LOAD ERROR");setTimeout(()=>location.href="index.html",1200)}